version: 2
updates:
  # action
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
  # npm包
  - package-ecosystem: "npm"
    directory: "www/"
    schedule:
      interval: "weekly"
  # 子模块
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
